config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :conversations,:only => [:show, :create]
resources :projects do
  resources :conversations
  resources :chat_messages
  resources :chat_users, :only => :index
    
  match 'chat_settings/:action' => 'chat_settings', :via => [:get, :post]
end

get 'projects/conversations/:id', :to => 'conversations#show'
get 'projects/:id/issues/conversations/:id', :to => 'conversations#show'
get 'projects/:id/settings/conversations/:id', :to => 'conversations#show'

resources :conversations do
  resources :chat_messages
end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
end

app/models/chat_setting.rb
class ChatSetting < ActiveRecord::Base
  unloadable

  belongs_to :project

  attr_accessible :name, :value, :project_id

  cattr_accessor :settings
  # Hash used to cache setting values
  @chat_cached_settings = {}  
  validates_uniqueness_of :name, :scope => [:project_id]

  # Returns the value of the setting named name
  def self.[](name, project_id)
    project_id = project_id.id if project_id.is_a?(Project)
    v = @chat_cached_settings[hk(name, project_id)]
    v ? v : (@chat_cached_settings[hk(name, project_id)] = find_or_default(name, project_id).value)
  end

  def self.[]=(name, project_id, v)
    project_id = project_id.id if project_id.is_a?(Project)
    setting = find_or_default(name, project_id)
    setting.value = (v ? v : "")
    @chat_cached_settings[hk(name, project_id)] = nil
    setting.save
    setting.value
  end
  
  private

    def self.hk(name, project_id)
      "#{name}-#{project_id.to_s}"
    end
    
    # Returns the Setting instance for the setting named name
    # (record found in database or new record with default value)
    def self.find_or_default(name, project_id)
      name = name.to_s
      setting = find_by_name_and_project_id(name, project_id)
      setting ||= new(:name => name, :value => '', :project_id => project_id)
    end
end

app/models/chat_user.rb
class ChatUser < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :conversation
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :project
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :chat_messages, dependent: :destroy

  validates_presence_of :project_id
  
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  before_action :set_chat_message, only: [:destroy]
  
  def create
    @conversation = Conversation.find(params[:conversation_id])
    @project = @conversation.project
    (render_403; return false) unless @project && @project.module_enabled?(:redmine_chat) && User.current.allowed_to?(:launch_chat, @project)
    
    @message = @conversation.chat_messages.build(message_params)
    @message.user_id = User.current.id
    @message.save!
    PrivatePub.publish_to "/chatroom", :conversation_id => @conversation.id, :project_id => @project.id
    @path = conversation_path(@conversation)
  end
  
  def index
    @project = Project.find(params[:project_id])
    (render_403; return false) unless @project && @project.module_enabled?(:redmine_chat)
    @limit =  10
    @conversation = @project.conversation
    @chat_messages = ChatMessage.where(conversation: @conversation)
    @chat_messages_count = @chat_messages.count
    @chat_messages_pages = Paginator.new @chat_messages_count, @limit, params['page']
    @offset ||= @chat_messages_pages.offset
    @chat_messages = @chat_messages.order("#{ChatMessage.table_name}.created_at DESC").
                      limit(@limit).
                      offset(@offset).
                      to_a
    respond_to do |format|
      format.html {
        @chat_message = ChatMessage.new # for adding chat_message inline
        render :layout => false if request.xhr?
      }
      format.api
      format.atom { render_feed(@chat_messages, :title => (@project ? @project.name : Setting.app_title) + ": #{l(:label_chat_messages)}") }
    end
  end

  def destroy
    if User.current.allowed_to?(:delete_chat_messages, @project) || (@chat_message.user == User.current && User.current.allowed_to?(:delete_own_chat_messages, @project))
      if @chat_message.destroy
        flash[:notice] = l(:notice_successful_delete)
      else
        flash[:error] = l(:notice_unsuccessful_save)
      end
      
      respond_to do |format|
        format.html { redirect_to :action => "index", :project_id => @chat_message.conversation.project }
        format.api  { head :ok }
      end
    else
      (render_403; return false)
    end
  end
  
  private
    def message_params
      params.require(:chat_message).permit(:body)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_chat_message
      @chat_message = ChatMessage.find(params[:id])
    end


end

app/controllers/chat_settings_controller.rb
class ChatSettingsController < ApplicationController
  unloadable
  before_action :find_project_by_project_id, :authorize

  def save
    (render_403; return false) unless @project.module_enabled?(:redmine_chat)
    if params[:chat_settings] && params[:chat_settings].is_a?(Hash) then
      settings = params[:chat_settings]
      settings.map do |k, v|
        ChatSetting[k, @project.id] = v
      end
    end
    redirect_to :controller => 'projects', :action => 'settings', :id => @project, :tab => params[:tab]
  end

end

app/controllers/chat_users_controller.rb
class ChatUsersController < ApplicationController
  unloadable

  before_action :find_optional_project, :only => :index
  before_action :clear_old_records, :only => :index

  def index
    @users = @project.users
    
    @conversation = @project.conversation
    @chat_messages = ChatMessage.where(conversation: @conversation).limit(5).reorder("#{ChatMessage.table_name}.created_at DESC").to_a
  end
  
  private
    def clear_old_records
      yesterday = Date.yesterday      
      old_chat_users = ChatUser.where("created_at <= ?", yesterday)
      old_chat_users.destroy_all 
    end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  layout false
  before_action :find_project_by_project_id, :only => [:create]

  def create
    (render_403; return false) unless @project.module_enabled?(:redmine_chat) && User.current.allowed_to?(:launch_chat, @project)
    if Conversation.where(:project_id => @project.id).present?
      @conversation = Conversation.where(:project_id => @project.id).first
    else
      @conversation = Conversation.create!(conversation_params)
      @conversation.project_id = @project.id
    end
    manual_flag = params[:manual]
    if manual_flag == "1"
      render json: { conversation_id: @conversation.id, manual: manual_flag }
    else 
      render json: { conversation_id: @conversation.id }
    end
  end

  def show
    @conversation = Conversation.find(params[:id])
    @project = @conversation.project
    (render_403; return false) unless @project && @project.module_enabled?(:redmine_chat) && User.current.allowed_to?(:launch_chat, @project)
    if (params[:manual] == "1")
      @manual_flag = true
    else
      @manual_flag = false
    end
    # get the setting's max number
    @limit = 5
    if !ChatSetting[:max_number_in_chat, @project.id].blank?
      @limit = ChatSetting[:max_number_in_chat, @project].to_i
    end
    @messages = ChatMessage.where(conversation: @conversation).limit(@limit).reorder("#{ChatMessage.table_name}.created_at DESC").to_a
    @messages.reverse!
    @message = ChatMessage.new
  end

  private
    def conversation_params
      params.permit(:sender_id, :project_id)
    end
  
    def interlocutor(conversation)
      User.current == conversation.recipient ? conversation.sender : conversation.recipient
    end
end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
  def self_or_other(message)
    message.user == User.current ? "self" : "other"
  end

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/chat_users_helper.rb
module ChatUsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == User.current ? conversation.sender : conversation.recipient
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/chat_messages/_chat_message.html.erb
<li class="<%= chat_message.user == User.current ? "self" : "other" %>">
  <div class="avatar">
  	<% if avatar(chat_message.user, :size => "32").blank? %>
    	<%= link_to_user(chat_message.user, :format => :username) %>
    <% else %>
    	<%= link_to(avatar(chat_message.user, :size => "32"), user_path(chat_message.user)) %>
    <% end %>
  </div>
  <div class="chatboxmessagecontent">
    <p><%= textilizable(chat_message.body) %></p>
    <time datetime="<%= chat_message.created_at %>" title="<%= chat_message.created_at.strftime("%d %b  %Y at %I:%M%p") %>">
      <%= chat_message.user.name %> • <%= chat_message.created_at.strftime("%H:%M %p") %>
    </time>
  </div>
</li>

app/views/chat_messages/create.js.erb
<% publish_to @path do %>
    var id = "<%= @conversation.id %>";
    var chatbox = $("#chatbox_" + id + " .chatboxcontent");
    var sender_id = "<%= @message.user.id %>";
    var reciever_id = $('meta[name=user-id]').attr("content");

    chatbox.append("<%= j render( partial: @message ) %>");
    chatbox.scrollTop(chatbox[0].scrollHeight);


    if (sender_id != reciever_id) {
        chatBox.chatWith(id);
        chatbox.children().last().removeClass("self").addClass("other");
        chatbox.scrollTop(chatbox[0].scrollHeight);
        chatBox.notify();
    }
<% end %>

app/views/chat_messages/index.html.erb
<div class="contextual">
</div>

<h2><%=l(:label_chat_messages)%></h2>

<% if @chat_messages.empty? %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <% @chat_messages.each do |chat_message| %>
    <h6><%= avatar(chat_message.user, :size => "24") %><%= authoring chat_message.created_at, chat_message.user %></h6>
    <%= textilizable(chat_message.body) %>
    <% if User.current.allowed_to?(:delete_chat_messages, @project) || (chat_message.user == User.current && User.current.allowed_to?(:delete_own_chat_messages, @project)) %>
    <p class="buttons">
      <%= link_to image_tag('delete.png'), project_chat_message_path(chat_message.conversation.project, chat_message),
                                                                      :data => {:confirm => l(:text_are_you_sure)},
                                                                      :method => :delete,
                                                                      :title => l(:button_delete) %>
    </p>
    <% end %>
  <% end %>
<% end %>
<span class="pagination"><%= pagination_links_full @chat_messages_pages %></span>

app/views/chat_users/index.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:launch_chat, @project) %>
    <%= link_to l(:label_launch_chat), "#", "data-sid" => User.current.id, "data-pid" => @project.id, :class => 'icon icon-add activate-conversation' %>
  <% end %>
</div>

<h2><%=l(:label_chat)%></h2>
<div class="splitcontentleft">
    <h3><%= l(:label_chat_users) %></h3>
    <div class="chat_user">
      <!-- Table -->
      <table class="table">
        <thead>
        <tr>
          <th>#</th>
          <th><%= l(:field_name) %></th>
          <th><%= l(:label_online_status) %></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= "#{avatar(user, :size => '14')}#{user ? link_to_user(user) : "-"}".html_safe %></td>
              <td>
              	<% if user == User.current || ChatUser.find_by(:project_id => @project.id, :user_id => user.id) %>
                  <%= image_tag('online.png', :plugin => "redmine_chat") %>
                <% else%>
                  <%= image_tag('offline.png', :plugin => "redmine_chat") %>
                <% end %>
               </td>
             </tr>
        <% end %>
      </tbody>
      </table>
    </div>
    <hr>
    <h3><%= l(:label_latest_conversations) %></h3>
    <div class="user_chat">
      <% if @chat_messages.any? %>
        <% if User.current.allowed_to?(:show_all_chat_messages, @project) %>
           <p><%= link_to l(:label_chat_messages_view_all), project_chat_messages_path(@project) %></p>
        <% end %>
        <% @chat_messages.each do |chat_message| %>
          <h6><%= avatar(chat_message.user, :size => "24") %><%= authoring chat_message.created_at, chat_message.user %></h6>
          <%= textilizable(chat_message.body) %>
        <% end %>
        <% if User.current.allowed_to?(:show_all_chat_messages, @project) %>
           <p><%= link_to l(:label_chat_messages_view_all), project_chat_messages_path(@project) %></p>
        <% end %>
      <% else %>
           <p><%=l(:tip_no_conversations)%></p>
      <% end %>
    </div>
</div>

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>
    <h1><%= @conversation.project.name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
</div>
<% if @manual_flag %>
	<div class="chatboxcontent">
<% else %>
	<div class="chatboxcontent" style="display: none;">
<% end %>
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<% if @manual_flag %>
	<div class="chatboxinput">
<% else %>
	<div class="chatboxinput" style="display: none;">
<% end %>
  <%= form_for([@conversation, @message], :remote => true, :html => { id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>
<audio id="chatAudio"><source src="/plugin_assets/redmine_chat/sounds/notification.mp3" type="audio/mpeg"></audio>
<%= subscribe_to conversation_path(@conversation), User.current, @project %>

app/views/layouts/_chat.html.erb
 <% if @project && @project.module_enabled?(:redmine_chat) && User.current %>
  <%= subscribe_to "/chatroom", User.current, @project %>
  <script>
    PrivatePub.subscribe("/chatroom", function(data, channel)
    {
      var current_user_id = '#{current_user.try(:id)}';
      if (data.receiver_id == current_user_id)
      {
        chatBox.chatWith(data.conversation_id);
      }
      else {
        chatBox.chatWith(data.conversation_id);
      }
    });
  </script>
  
  <script>
    $(document).ready(function(){
    	var project_id = $.jStorage.get('project_id');
    	if (project_id == null || project_id == '') {
    		project_id = <%= @project.id %>;
    		$.jStorage.set('project_id',project_id);
    		$.jStorage.setTTL("project_id", 25000);
    	}
    	if (project_id != <%= @project.id %>) {
    		$.jStorage.deleteKey('chatbox_div');
    	}
    	var chatbox = $('.chatbox')
    	var chatbox_div = $.jStorage.get('chatbox_div');
    	if (chatbox.length == 0 && chatbox_div != null) {
    		$(document.body).append(chatbox_div);
    	} 
    	<% if ChatSetting[:chat_auto_pop_on_load, @project.id].to_i > 0 %>
    	else {
	        var project_id = <%= @project.id %>;
			var sender_id = <%= User.current.id %>;
        	$.post("/conversations", { sender_id: sender_id, project_id: project_id }, function (data) {
            chatBox.chatWith(data.conversation_id);
        	});
       	}
       	<% end %>
    });
  </script>
<% end %>

app/views/layouts/_chat_head.html.erb
<% if @project && @project.module_enabled?(:redmine_chat) && User.current %>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= User.current.id %>' name='user-id'/>

  <script>
    $(window).unload(function(){
    	<% if @project %>
    		var project_id = <%= @project.id %>;
    		$.jStorage.set('project_id',project_id);
    		$.jStorage.setTTL('project_id', 25000);
    	<% end %> 
    	<% if @project.conversation %>
    		<% conversation_id = @project.conversation.id %>
			var chatbox_div = $('#chatbox_<%= conversation_id %>').prop("outerHTML");
        	if (chatbox_div != undefined) {
        		$.jStorage.set('chatbox_div',chatbox_div);
        		$.jStorage.setTTL('chatbox_div', 25000);
        	}
        <% end %>
	});
  </script>
  <%= javascript_include_tag :private_pub, :plugin => 'redmine_chat', media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag :redmine_chat, :plugin => 'redmine_chat', media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag :chat, :plugin => 'redmine_chat', media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag :users, :plugin => 'redmine_chat', media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag "bootstrap.min.js", :plugin => 'redmine_chat', media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag "json2.js", :plugin => 'redmine_chat', media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag "jstorage.js", :plugin => 'redmine_chat', media: 'all', 'data-turbolinks-track' => true  %>
  <%= stylesheet_link_tag "redmine_chat.css", :plugin => 'redmine_chat' %>
  <%= stylesheet_link_tag "font-awesome.min.css", :plugin => 'redmine_chat' %>
  <%= stylesheet_link_tag "chat.css", :plugin => 'redmine_chat' %>
<% end %>

app/views/projects/_chat_settings.html.erb
<%= form_tag({:controller => "chat_settings", :action => "save", :project_id => @project, :tab => 'chat'}, :method => :post, :class => "tabular") do %>
  <div class="tabular box">
    <p>
      <label><%= l(:label_chat_auto_pop_on_load) %></label>
      <%= hidden_field_tag('chat_settings[chat_auto_pop_on_load]', 0)  %>
      <%= check_box_tag 'chat_settings[chat_auto_pop_on_load]', 1, ChatSetting[:chat_auto_pop_on_load, @project.id].to_i > 0 %>
    </p>
    
    <p>
  	  <label><%= l(:label_max_number_in_chat) %></label>
  	  <%= select_tag 'chat_settings[max_number_in_chat]',  options_for_select([["5", "5"],
                                                                     ["10", "10"],
                                                                     ["20", "20"],
                                                                     ["40", "40"],
                                                                     ["80", "80"],
                                                                     ["100", "100"]], ChatSetting[:max_number_in_chat, @project.id]) %>
	</p>
    
  </div>

  <%= submit_tag l(:button_save) %>
<% end %>